/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.espe.edu.ec.Ventanas;

import com.espe.edu.ec.Clases.ConexionMySql;
import com.espe.edu.ec.Clases.Operaciones;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author solan
 */
public class Programa extends javax.swing.JFrame {

    /**
     * Creates new form Programa
     */
    
    String fecha, hora;
    private String setCurrentUser;
    ConexionMySql con = new ConexionMySql();
    Operaciones op = new Operaciones();
    
    public Programa() {
        initComponents();
        cargar();
        ValidacionTipeo();
    }

    public void cargar() {
        DefaultTableModel modeloCliente = (DefaultTableModel) c.getModel();
        c.setModel(con.cargarDatosCliente(modeloCliente));
        System.out.println("Inciado componentes :D ");
    }

    public void recargar() {
        DefaultTableModel modelotc = (DefaultTableModel) c.getModel();
        int ntc = modelotc.getRowCount();
        for (int i = 0; i < ntc; i++) {
            modelotc.removeRow(0);
        }
        cargar();
    }
    
    public void ValidacionTipeo() {
        gesCli_txCedula.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {
                char c = ke.getKeyChar();
                if (Character.isLetter(c)) {
                    Toolkit.getDefaultToolkit().beep();
                    ke.consume();
                }
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        gesCli_txNombre.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {
                char c = ke.getKeyChar();
                if (Character.isDigit(c)) {
                    Toolkit.getDefaultToolkit().beep();
                    ke.consume();
                }
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        gesCli_txApellido.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {
                char c = ke.getKeyChar();
                if (Character.isDigit(c)) {
                    Toolkit.getDefaultToolkit().beep();
                    ke.consume();
                }
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PnlGestClien = new javax.swing.JPanel();
        Spn_GesCl = new javax.swing.JTabbedPane();
        gesCli_Visualizar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        c = new javax.swing.JTable();
        gesCli_btnBuscar = new javax.swing.JButton();
        gesCli_txBuscar = new javax.swing.JTextField();
        gesCli_btnEliminar = new javax.swing.JButton();
        gesCli_btnModificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        gesCli_Ingreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gesCli_btnGuardar = new javax.swing.JButton();
        gesCli_txCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gesCli_txNombre = new javax.swing.JTextField();
        gesCli_txApellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        gesCli_txApellidoMaterno = new javax.swing.JTextField();
        gesCli_txTeleFijo = new javax.swing.JTextField();
        gesCli_txCelular = new javax.swing.JTextField();
        gesCli_txDireccion = new javax.swing.JTextField();
        gesCli_txCorreo = new javax.swing.JTextField();
        gesCli_btnGuardar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(240, 189, 172));

        Spn_GesCl.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        c.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "C.I", "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono Fijo", "Celular", "Direccion", "Correo"
            }
        ));
        c.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(c);

        gesCli_btnBuscar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        gesCli_btnBuscar.setText("Buscar");
        gesCli_btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gesCli_btnBuscarActionPerformed(evt);
            }
        });

        gesCli_btnEliminar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        gesCli_btnEliminar.setText("Eliminar");
        gesCli_btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gesCli_btnEliminarActionPerformed(evt);
            }
        });

        gesCli_btnModificar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        gesCli_btnModificar.setText("Modificar");
        gesCli_btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gesCli_btnModificarActionPerformed(evt);
            }
        });

        jLabel10.setText("Ingrese N.- Cedula: ");

        javax.swing.GroupLayout gesCli_VisualizarLayout = new javax.swing.GroupLayout(gesCli_Visualizar);
        gesCli_Visualizar.setLayout(gesCli_VisualizarLayout);
        gesCli_VisualizarLayout.setHorizontalGroup(
            gesCli_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gesCli_VisualizarLayout.createSequentialGroup()
                .addGroup(gesCli_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gesCli_VisualizarLayout.createSequentialGroup()
                        .addGroup(gesCli_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gesCli_VisualizarLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(gesCli_btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(gesCli_btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(gesCli_VisualizarLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gesCli_txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(gesCli_btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 554, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        gesCli_VisualizarLayout.setVerticalGroup(
            gesCli_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gesCli_VisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gesCli_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(gesCli_txBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gesCli_btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(gesCli_VisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gesCli_btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gesCli_btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        Spn_GesCl.addTab("Visualizar", gesCli_Visualizar);

        jLabel1.setText("Cedula: ");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido Paterno:");

        gesCli_btnGuardar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        gesCli_btnGuardar.setText("Guardar");
        gesCli_btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gesCli_btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel4.setText("INGRESO DE CLIENTES");

        jLabel5.setText("Apellido Materno:");

        jLabel6.setText("Telefono Fijo:");

        jLabel7.setText("Celular:");

        jLabel8.setText("Direccion:");

        jLabel9.setText("Correo:");

        gesCli_btnGuardar1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        gesCli_btnGuardar1.setText("Nuevo");
        gesCli_btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gesCli_btnGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gesCli_IngresoLayout = new javax.swing.GroupLayout(gesCli_Ingreso);
        gesCli_Ingreso.setLayout(gesCli_IngresoLayout);
        gesCli_IngresoLayout.setHorizontalGroup(
            gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gesCli_IngresoLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel4)
                .addContainerGap(686, Short.MAX_VALUE))
            .addGroup(gesCli_IngresoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gesCli_IngresoLayout.createSequentialGroup()
                        .addComponent(gesCli_btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gesCli_btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(gesCli_IngresoLayout.createSequentialGroup()
                        .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gesCli_txCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gesCli_txDireccion)
                            .addComponent(gesCli_txCelular, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gesCli_txTeleFijo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gesCli_txApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(gesCli_txCedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gesCli_txNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gesCli_txApellidoMaterno, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(104, 104, 104))))
        );
        gesCli_IngresoLayout.setVerticalGroup(
            gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gesCli_IngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gesCli_IngresoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(gesCli_IngresoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(gesCli_txCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(gesCli_txNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(gesCli_txApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(gesCli_txApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gesCli_txTeleFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gesCli_txCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gesCli_txDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(gesCli_txCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gesCli_IngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gesCli_btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gesCli_btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Spn_GesCl.addTab("Ingreso", gesCli_Ingreso);

        javax.swing.GroupLayout PnlGestClienLayout = new javax.swing.GroupLayout(PnlGestClien);
        PnlGestClien.setLayout(PnlGestClienLayout);
        PnlGestClienLayout.setHorizontalGroup(
            PnlGestClienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Spn_GesCl)
        );
        PnlGestClienLayout.setVerticalGroup(
            PnlGestClienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Spn_GesCl)
        );

        jTabbedPane1.addTab("Gestion de Clientes", PnlGestClien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gesCli_btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gesCli_btnBuscarActionPerformed
        if (gesCli_txBuscar.getText().equals("")) {
                   JOptionPane.showMessageDialog(c, "Pon algo para buscar prro :'v ");
               } else {
                   JOptionPane.showMessageDialog(c, con.buscarCliente(gesCli_txBuscar.getText()));
               }        
    }//GEN-LAST:event_gesCli_btnBuscarActionPerformed

    private void gesCli_btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gesCli_btnEliminarActionPerformed
        DefaultTableModel model = (DefaultTableModel) c.getModel();
        int a = c.getSelectedRow();

        if (a < 0) {
            JOptionPane.showMessageDialog(null,
                "Debe seleccionar una fila de la tabla");
        } else {
            int confirmar = JOptionPane.showConfirmDialog(null,
                "Esta seguro que desea Eliminar el registro? ");
            if (JOptionPane.OK_OPTION == confirmar) {
                if (con.eliminarCliente("" + model.getValueAt(a, 1)) == 1) {
                    JOptionPane.showMessageDialog(null, "Registro Eliminado");
                } else {
                    JOptionPane.showMessageDialog(null, "Registro No se puede eliminar");
                }
                recargar();
            }
        }
    }//GEN-LAST:event_gesCli_btnEliminarActionPerformed

    private void gesCli_btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gesCli_btnModificarActionPerformed
        DefaultTableModel model = (DefaultTableModel) c.getModel();
        int a = c.getSelectedRow();
        if (a < 0) {
            JOptionPane.showMessageDialog(null,
                "Debe seleccionar una fila de la tabla");
        } else {
            String fijo = JOptionPane.showInputDialog(c, "Ingrese nuevo telefono: ", "Modificacion Telefono Fijo", 1);
            //String celu = JOptionPane.showInputDialog(c, "Ingrese nuevo celular: ", "Modificacion Celular", 2);
            //String direccion = JOptionPane.showInputDialog(c, "Ingrese nueva direccion: ", "Modificacion Direccion", 3);
            //String correo = JOptionPane.showInputDialog(c, "Ingrese nuevo correo: ", "Modificacion Correo", 4);
            if (fijo.equals("")) {
                JOptionPane.showMessageDialog(null, "Registro No modificado");
            }else if (con.modificarCliente("" + model.getValueAt(a, 5), fijo) == 1){
            //} else if (con.modificarCliente((("" + model.getValueAt(a, 5), fijo) == 1),(("" + model.getValueAt(a, 6), celu == 2)), (("" + model.getValueAt(a, 7), direccion == 3)), (("" + model.getValueAt(a, 8), correo) == 4))){
                JOptionPane.showMessageDialog(null, "Registro Modificado");
            } else {
                JOptionPane.showMessageDialog(null, "Registro No modificado");
            }
            recargar();
        }
    }//GEN-LAST:event_gesCli_btnModificarActionPerformed

    private void gesCli_btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gesCli_btnGuardarActionPerformed
        if (gesCli_txCedula.getText().equals("") || gesCli_txNombre.getText().equals("") || gesCli_txApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Uno o mas campos vacios");
        } else if (op.validadorDeCedula(gesCli_txCedula.getText())) {
            String respuesta = con.buscarCliente(gesCli_txCedula.getText());
            System.out.println("Respuesta: " + respuesta);
            if (respuesta.equals("No existe registro")) {
                con.IngresoClientes(gesCli_txCedula.getText(), gesCli_txNombre.getText(), gesCli_txApellido.getText(),gesCli_txApellidoMaterno.getText(),gesCli_txTeleFijo.getText(),
                        gesCli_txCelular.getText(), gesCli_txDireccion.getText(), gesCli_txCorreo.getText());
                recargar();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Usuario ya Existente");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "CI Incorrecta");
        }

    }//GEN-LAST:event_gesCli_btnGuardarActionPerformed

    private void gesCli_btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gesCli_btnGuardar1ActionPerformed
        // TODO add your handling code here:
        gesCli_txCedula.setText("");
        gesCli_txNombre.setText("");
        gesCli_txApellido.setText("");
        gesCli_txApellidoMaterno.setText("");
        gesCli_txTeleFijo.setText("");
        gesCli_txCelular.setText("");
        gesCli_txDireccion.setText("");
        gesCli_txCorreo.setText("");
    }//GEN-LAST:event_gesCli_btnGuardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlGestClien;
    private javax.swing.JTabbedPane Spn_GesCl;
    public javax.swing.JTable c;
    private javax.swing.JPanel gesCli_Ingreso;
    private javax.swing.JPanel gesCli_Visualizar;
    private javax.swing.JButton gesCli_btnBuscar;
    private javax.swing.JButton gesCli_btnEliminar;
    private javax.swing.JButton gesCli_btnGuardar;
    private javax.swing.JButton gesCli_btnGuardar1;
    private javax.swing.JButton gesCli_btnModificar;
    private javax.swing.JTextField gesCli_txApellido;
    private javax.swing.JTextField gesCli_txApellidoMaterno;
    private javax.swing.JTextField gesCli_txBuscar;
    private javax.swing.JTextField gesCli_txCedula;
    private javax.swing.JTextField gesCli_txCelular;
    private javax.swing.JTextField gesCli_txCorreo;
    private javax.swing.JTextField gesCli_txDireccion;
    private javax.swing.JTextField gesCli_txNombre;
    private javax.swing.JTextField gesCli_txTeleFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
